### ISSUE TITLE
element-ui cdn引入的方式

### ISSUE THREAD

**Issue by Pinkagit** [lmxdawn/vue-admin-html#7]
看了下element-ui 除了cdn引入外还通过包管理下载，感觉element引入使用的还是通过包管理下载的。
我试了下把包里的element-ui删了，运行报错：
![image](https://user-images.githubusercontent.com/31717702/56355093-0b476700-6208-11e9-8f31-004397256c51.png)

**Comment by lmxdawn** [comment]
vue.config.js 配置文件里面有剔除的 ：
```
if (process.env.NODE_ENV === "production") {
    // 为生产环境修改配置...
    config.externals = {
        vue: "Vue",
        vuex: "Vuex",
        "vue-router": "VueRouter",
        "element-ui": "ELEMENT" // 这里就是剔除 element-ui 的
    };
}
```

**Comment by Pinkagit** [comment]
多谢解答，是我对webpack学习不深，受教了
