### ISSUE TITLE
请问如何去掉mock变成请求php的接口

### ISSUE THREAD

**Issue by 774649283** [lmxdawn/vue-admin-html#8]
我把import mock这里注释掉了  想改成请求后端接口 但是页面报403。能把如何使用后端接口的配置说明一下吗

**Comment by 774649283** [comment]
已经解决

**Comment by coderzhw** [comment]
> 已经解决

怎么解决的?

**Comment by 774649283** [comment]
直接删除mock文件夹，删除main.js的导入 @coderzhw

**Comment by coderzhw** [comment]
能不能留个qq，我这边还是没启动，麻烦求教下

**Comment by coderzhw** [comment]
@774649283

**Comment by coderzhw** [comment]
总是报验证失败，重新登陆的错误 @774649283

**Comment by 774649283** [comment]
明天帮你看哈，1176229277 @coderzhw

**Comment by coderzhw** [comment]
> 明天帮你看哈，1176229277 @coderzhw

多谢老哥，我自己摸索出来了~

**Comment by 774649283** [comment]
可以的 @coderzhw 很nice

**Comment by lmxdawn** [comment]
main.js &nbsp;里面注释 mock 的引入



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 静水流深 <notifications@github.com&gt;
发送时间: 2020年3月17日 19:38
收件人: lmxdawn/vue-admin-html <vue-admin-html@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[lmxdawn/vue-admin-html] 请问如何去掉mock变成请求php的接口 (#8)





  
已经解决
  
怎么解决的?

**Comment by GGGGGuoyufei** [comment]
这是什么？我为什么会收到这个信息？





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 静水流深 <notifications@github.com&gt;
发送时间: 2020年3月17日 19:38
收件人: lmxdawn/vue-admin-html <vue-admin-html@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[lmxdawn/vue-admin-html] 请问如何去掉mock变成请求php的接口 (#8)





  
已经解决
  
怎么解决的?
